name: leading

description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  beamer: ^0.12.4
  blobs: 
    git: 
      url: https://github.com/ryanheise/flutter_blobs.git
      ref: nnbd
  bloc: ^7.0.0
  dots_indicator: ^2.0.0
  equatable: ^2.0.0
  firebase_core: ^1.1.1
  firebase_database: ^7.0.0-dev.2
  flutter_beacon:
    git:
      url: https://github.com/alann-maulana/flutter_beacon.git
  flutter_bloc: ^7.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  get_it: ^7.1.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  permission_handler: ^8.0.0
  platform_device_id: ^1.0.1
  smooth_page_indicator: ^0.3.0-nullsafety.0
  uuid: ^3.0.4
  very_good_analysis: ^2.0.3
  vibration: ^1.7.4-nullsafety.0
  flutter_beep: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.2
  flutter_launcher_icons: ^0.9.0


flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/icon/background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/forground.png" # only available for Android 8.0 devices and above

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icon/
    - assets/icon/icon_dark.png
  fonts:
    - family: Karla
      fonts:
        - asset: fonts/Karla-Bold.ttf
          weight: 700
