name: leading

description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  beamer: ^0.12.4
  bloc: ^7.0.0
  coast: ^2.0.1
  dots_indicator: ^2.0.0
  equatable: ^2.0.0
  firebase_core: ^1.1.1
  firebase_database: ^7.0.0-dev.2
  flutter_beacon: ^0.5.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  get_it: ^7.1.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  loading_indicator: ^2.1.1
  permission_handler: ^8.0.0
  platform_device_id: ^1.0.1
  uuid: ^3.0.4
  very_good_analysis: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.2

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true

assets:
  - assets/
fonts:
  - family: Sofia Pro
    fonts:
      - asset: fonts/sofia-pro-ultralight.otf
        weight: 100
      - asset: fonts/sofia-pro-extralight.otf
        weight: 200
      - asset: fonts/sofia-pro-light.otf
        weight: 300
      - asset: fonts/sofia-pro-regular.otf
        weight: 400
      - asset: fonts/sofia-pro-medium.otf
        weight: 500
      - asset: fonts/sofia-pro-semibold.otf
        weight: 600
      - asset: fonts/sofia-pro-bold.otf
        weight: 700
      - asset: fonts/sofia-pro-black.otf
        weight: 800
